openapi: 3.0.2
info:
  description: Tilgjengeliggjør forhåndsvisning av online resurser
  version: '1.0.0'
  title: Dataset Preview API
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
servers:
  - url: 'https://data.norge.no/dataset/preview'
    description: Produksjonsversjon av API server
paths:
  /preview:
    post:
      description: Hent preview av online resurs
      operationId: preview
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preview'
        '400':
          description: Ugyldig forespørsel
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreviewRequest'


components:
  schemas:
    PreviewRequest:
      type: object
      description: Preview forespørsel
      required:
        - url
        - rows
      properties:
        url:
          type: string
          format: uri
          pattern: "^https?://"
          description: url til online resurs
        rows:
          type: integer
          description: antall rader som skal lastes
    Preview:
      type: object
      description: Preview
      properties:
        table:
          $ref: '#/components/schemas/Table'
        plain:
          type: string
          description: plain tekst
    Table:
      type: object
      description: Table
      properties:
        header:
          $ref: '#/components/schemas/TableHeader'
        rows:
          type: array
          items:
            $ref: '#/components/schemas/TableRow'
    TableHeader:
      type: object
      description: Table header
      properties:
        columns:
          type: array
          items:
            type: string
    TableRow:
      type: object
      description: Table row
      properties:
        columns:
          type: array
          items:
            type: string

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - apiKey: []
