application:
  api-key: ${API_KEY:}
  allowedOrigins: ${ALLOWED_ORIGINS:}

logging:
  level.root: WARN
  level.no.fdk: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  metrics:
    tags:
      application: fdk-dataset-preview-service

---
spring:
  config.activate.on-profile: develop

---
spring:
  config.activate.on-profile: integration-test
application:
  api-key: my-api-key
  allowedOrigins: http://localhost:5000
