apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: fdk-dataset-preview-service
  name: fdk-dataset-preview-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: fdk-dataset-preview-service
