---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: fdk-dataset-preview-service
  name: fdk-dataset-preview-service
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: fdk-dataset-preview-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: fdk-dataset-preview-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: fdk-dataset-preview-service
          image: fdk-dataset-preview-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "750Mi"
              cpu: "10m"
            limits:
              memory: "750Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
