---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fdk-dataset-preview-service-deployment.yaml
  - fdk-dataset-preview-service-service.yaml
images:
  - name: fdk-dataset-preview-service
    newName: ghcr.io/informasjonsforvaltning/fdk-dataset-preview-service
    newTag: $(GIT_COMMIT_SHA)
